Dwello_App/Controllers/HostController.cs
using Dwello_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dwello_App.Controllers
{
    public class HostController : Controller
    {
        private readonly DwelloContext _db;
        public HostController(DwelloContext db)
        {
            _db = db;
        }

        public IActionResult HostIndex()
        {
            return View();
        }
        public IActionResult LoggedInHostIndex()
        {
            return View();
        }

        public IActionResult Index(int? id)
        {
            if (id== null || id== 0)
            {
                return NotFound();
            }

            Models.Host? host = _db.Hosts.Include(host => host.Users).FirstOrDefault(host => host.UserId == id);

            if (host == null)
            {   
                return NotFound();
            }


            return View(host);
        }
    }
}

Dwello_App/Controllers/UserController.cs
using Dwello_App.Models;
using Microsoft.AspNetCore.Mvc;

namespace Dwello_App.Controllers
{
    public class UserController : Controller
    {
        private readonly DwelloContext _db;
        public UserController(DwelloContext db)
        {
            _db = db;
        }

        public IActionResult LoggedInUserIndex()
        {
            List<User> users = _db.Users.ToList();
            return View(users);
        }

        public IActionResult UserIndex()
        {
            return View();
        }

        public IActionResult UserEdit(int? UserId)
        {
            
            if (UserId == null || UserId == 0)
            {
                return NotFound();
            }

            User userFromDb = _db.Users.Find(UserId);

            if (userFromDb == null)
            {
                return NotFound();
            }
            return View(userFromDb);
            
        }
    }
}

Dwello_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dwello_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dwello_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dwello_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="LoggedInUserIndex">UserProfile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Host" asp-action="LoggedInHostIndex">HostProfile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="UserIndex"> OtherUserProfile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Host" asp-action="HostIndex"> OtherHostProfile</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Dwello_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>