Dwello_App/Models/Host.cs
using System.ComponentModel.DataAnnotations;

namespace Dwello_App.Models
{
    public class Host
    {
        [Required]
        [Key]
        public int HostId { get; set; }
        public int UserId { get; set; }
        public int HostRating { get; set; }

        public ICollection<User> Users { get; set; }
    }
}

Dwello_App/Controllers/HostController.cs
using Dwello_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dwello_App.Controllers
{
    public class HostController : Controller
    {
        private readonly DwelloContext _db;
        public HostController(DwelloContext db)
        {
            _db = db;
        }

        public IActionResult HostIndex()
        {
            return View();
        }
        public IActionResult LoggedInHostIndex()
        {
            return View();
        }

        public IActionResult Index(int? id)
        {
            if (id== null || id== 0)
            {
                return NotFound();
            }

            Models.Host? host = _db.Hosts.Include(host => host.Users).FirstOrDefault(host => host.UserId == id);

            if (host == null)
            {   
                return NotFound();
            }


            return View(host);
        }
    }
}

Dwello_App/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dwello_App.Models;

namespace Dwello_App.Controllers
{
    public class ListingsController : Controller
    {
        private readonly DwelloContext _context;

        public ListingsController(DwelloContext context)
        {
            _context = context;
        }

        // GET: Listings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Listings.ToListAsync());
        }

        // GET: Listings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listings = await _context.Listings
                .FirstOrDefaultAsync(m => m.ListingId == id);
            if (listings == null)
            {
                return NotFound();
            }

            return View(listings);
        }

        // GET: Listings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Listings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ListingId,HostId,Title,Location,Price,Status,Description,Type")] Listings listings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(listings);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(listings);
        }

        // GET: Listings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listings = await _context.Listings.FindAsync(id);
            if (listings == null)
            {
                return NotFound();
            }
            return View(listings);
        }

        // POST: Listings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ListingId,HostId,Title,Location,Price,Status,Description,Type")] Listings listings)
        {
            if (id != listings.ListingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(listings);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ListingsExists(listings.ListingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(listings);
        }

        // GET: Listings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listings = await _context.Listings
                .FirstOrDefaultAsync(m => m.ListingId == id);
            if (listings == null)
            {
                return NotFound();
            }

            return View(listings);
        }

        // POST: Listings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var listings = await _context.Listings.FindAsync(id);
            if (listings != null)
            {
                _context.Listings.Remove(listings);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ListingsExists(int id)
        {
            return _context.Listings.Any(e => e.ListingId == id);
        }
    }
}

Dwello_App/Views/Host/HostIndex.cshtml
@model Host

<h1>Host Profile of Others</h1> 
<hr />
<br />


<div class="profile-column">
    <div class="profile">
        <img src="#">
        <h2 class="first-name">HostFirstName</h2>
        <h4>Host</h4>
    </div>
    <br /> <br />
    <div class="side-profile">
        <div class="reviews">
            <p class="no-of-reviews">0</p>
            <h5>Reviews</h5>
        </div>

        <div class="rating">
            <p class="total-rating">4.88</p>
            <h5>Rating</h5>
        </div>

        <div class="date">
            <p class="date-joined">January 1, 2000</p>
            <h5> Started Hosting </h5>        
        </div>
    </div>
</div>

<br />
<hr />
<br />

<div class="user-info-column">
    <h1>About Host FirstName</h1>

    <ul class="additional-info">
        <li><p> Lives in Address</p></li>
    </ul>

    <p>UserDescription- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<br />
<hr />
<br />

<h2>Host Listing's Reviews </h2>
<div class="review-container">
    <p class="feedback"> "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna..."</p>
    <img src="#" alt="Profile Picture" />
    <p class="review-user-name">UserFirstName</p>
    <p class="review-date">December 2024</p>
</div>
<a asp-controller="Review" asp-action="ReviewIndex" asp-route-id="" class="outline-btn">Show More Reviews</a>

<br />
<hr />
<br />

<h2> Listings </h2>
<div class="listings-container">
    <img src="#" alt="Listing Image" />
    <p class="listing-type">Condo</p>
    <p class="listing-rating">4.9</p>
    <p class="listing-location">Cebu City</p>
</div>
<a asp-controller="Listing" asp-action="ListingIndex" asp-route-id="" class="outline-btn">View All NoOfHostListing's Listings</a>

Dwello_App/Views/Host/LoggedInHostIndex.cshtml
<h1>Logged-In User's Host Profile</h1>
<br />

<hr />
<ul>
    <li><a asp-controller="Bookings" asp-action="" class="outline-btn">Reservations</a>   </li>
    <li><a asp-controller="Listings" asp-action="" class="outline-btn">Listings</a>    </li>
    <li><a asp-controller="Listings" asp-action="" class="outline-btn">Earnings</a>    </li>
</ul>
<hr />

<br />
<h2>Welcome Logged-In HostFirstName</h2>
<br />

<a asp-controller="Listing" asp-action="AddListing" asp-route-id="" class="outline-btn">Create Listing</a>

<br />
<br />

<h3>Your Reservations</h3>
<a asp-controller="Bookings" asp-action="" class="outline-btn">All reservations (0)</a>

<br />

<ul>
    <li><a asp-controller="Bookings" asp-action="" class="outline-btn">Checking Out</a>    </li>
    <li><a asp-controller="Bookings" asp-action="" class="outline-btn">Currently Hosting</a>    </li>
    <li><a asp-controller="Bookings" asp-action="" class="outline-btn">Completed</a>    </li>
    <li><a asp-controller="Bookings" asp-action="" class="outline-btn">Cancelled</a>    </li>
    <li><a asp-controller="Bookings" asp-action="" class="outline-btn">All</a>    </li>
</ul>

<div class="listings-container">
    <img src="#" alt="Listing Image" />
    <p class="listing-type">Condo</p>
    <p class="listing-rating">4.9</p>
    <p class="listing-location">Cebu City</p>
</div>